const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

/**
 * Generates a PDF report and pipes it to the response stream
 * @param {Object} res - Express response stream
 * @param {Object} params - PDF parameters
 * @param {string} params.reportTitle - Title of the report
 * @param {string} params.generatedBy - Name of creator
 * @param {Object} params.filters - Key-value pair of filters applied
 * @param {Array<string>} params.headers - Table headers
 * @param {Array<string>} params.keys - Column keys
 * @param {Array<Object>} params.rows - Table data rows
 * @param {string} params.filename - Export filename
 */
const generatePDF = (res, { reportTitle, generatedBy, filters, headers, keys, rows, filename = "report.pdf" }) => {
    const doc = new PDFDocument({ margin: 40, size: "A4", bufferPages: true });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    doc.pipe(res);

    // Draw header on every page using the end-of-page rendering (bufferPages)
    const drawHeaderAndFooter = () => {
        const pages = doc.bufferedPageRange();
        for (let i = 0; i < pages.count; i++) {
            doc.switchToPage(i);

            // 1. Header (Logo & Company Title)
            const logoPath = path.join(__dirname, "../../frontend/src/assets/Softspire_Logo.png");
            if (fs.existsSync(logoPath)) {
                try {
                    doc.image(logoPath, 40, 25, { width: 45 });
                } catch (e) {
                    // Fallback text if image parsing fails
                    doc.fillColor("#1E293B").fontSize(18).text("S", 40, 25, { bold: true });
                }
            }

            doc.fillColor("#1E293B");
            doc.font("Helvetica-Bold").fontSize(18).text("Softspire", 95, 25);
            doc.font("Helvetica").fontSize(9).fillColor("#64748B").text("Employee Management System", 95, 45);

            // Divider Line
            doc.moveTo(40, 75).lineTo(555, 75).strokeColor("#CBD5E1").lineWidth(1).stroke();

            // Page Number
            doc.font("Helvetica").fontSize(8).fillColor("#94A3B8");
            doc.text(`Page ${i + 1} of ${pages.count}`, 40, 805, { align: "center", width: 515 });
            doc.text(`Generated by: ${generatedBy} | Date: ${new Date().toLocaleString()}`, 40, 805, { align: "left" });
        }
    };

    // Metadata section on page 1
    doc.y = 90;
    doc.fillColor("#0F172A").font("Helvetica-Bold").fontSize(14).text(reportTitle, 40, 90);
    doc.moveDown(0.5);

    // Filters Summary Card
    doc.fillColor("#F8FAFC").rect(40, doc.y, 515, 40).fill().strokeColor("#E2E8F0").lineWidth(1).stroke();
    const currentY = doc.y;
    doc.fillColor("#334155").font("Helvetica-Bold").fontSize(9).text("Filters Applied:", 50, currentY + 8);

    let filterText = "None";
    if (filters && Object.keys(filters).length > 0) {
        filterText = Object.entries(filters)
            .flatMap(([k, v]) => (v !== undefined && v !== null && v !== "") ? [`${k}: ${v}`] : [])
            .join("  |  ");
    }
    doc.font("Helvetica").text(filterText || "None", 50, currentY + 22);

    doc.y = currentY + 55;

    // Draw Table
    const tableTop = doc.y;
    const availableWidth = 515;
    const colWidth = availableWidth / headers.length;

    // Table Header
    doc.fillColor("#3B82F6").rect(40, tableTop, availableWidth, 22).fill();
    doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(9);

    headers.forEach((header, index) => {
        doc.text(header, 42 + index * colWidth, tableTop + 6, {
            width: colWidth - 4,
            align: "left",
            lineBreak: false
        });
    });

    let currentTableY = tableTop + 22;

    // Table Rows
    rows.forEach((row, rowIndex) => {
        // Pre-format all cell values for this row and calculate max cell height
        let rowHeight = 20; // default minimum row height
        const formattedRow = {};

        doc.font("Helvetica").fontSize(8);
        keys.forEach((key) => {
            let val = row[key];
            if (val === undefined || val === null) {
                val = "";
            } else {
                const dateKeys = ["joining_date", "date", "start_date", "end_date", "due_date"];
                if (dateKeys.includes(key)) {
                    const d = new Date(val);
                    if (!isNaN(d.getTime())) {
                        const yyyy = d.getFullYear();
                        const mm = String(d.getMonth() + 1).padStart(2, "0");
                        const dd = String(d.getDate()).padStart(2, "0");
                        const hh = String(d.getHours()).padStart(2, "0");
                        const min = String(d.getMinutes()).padStart(2, "0");
                        const ss = String(d.getSeconds()).padStart(2, "0");

                        if (hh === "00" && min === "00" && ss === "00") {
                            val = `${yyyy}-${mm}-${dd}`;
                        } else {
                            val = `${yyyy}-${mm}-${dd} ${hh}:${min}`;
                        }
                    }
                }

                if (typeof val === "string" && val.length > 28) {
                    val = val.substring(0, 25) + "...";
                }
            }
            formattedRow[key] = String(val);

            // Measure height of this text cell
            const cellTextHeight = doc.heightOfString(formattedRow[key], {
                width: colWidth - 4,
                align: "left"
            });
            const cellHeight = cellTextHeight + 12; // 6pt padding top and bottom
            if (cellHeight > rowHeight) {
                rowHeight = cellHeight;
            }
        });

        // Page break safety check
        if (currentTableY + rowHeight > 760) {
            doc.addPage();
            currentTableY = 90; // Start below the header block area on subsequent pages
            // Draw table header again on new page
            doc.fillColor("#3B82F6").rect(40, currentTableY, availableWidth, 22).fill();
            doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(9);
            headers.forEach((header, index) => {
                doc.text(header, 42 + index * colWidth, currentTableY + 6, {
                    width: colWidth - 4,
                    align: "left",
                    lineBreak: false
                });
            });
            currentTableY += 22;
        }

        // Draw zebra background
        if (rowIndex % 2 === 1) {
            doc.fillColor("#F8FAFC").rect(40, currentTableY, availableWidth, rowHeight).fill();
        }

        // Row border
        doc.moveTo(40, currentTableY + rowHeight).lineTo(555, currentTableY + rowHeight).strokeColor("#F1F5F9").lineWidth(0.5).stroke();

        doc.fillColor("#334155").font("Helvetica").fontSize(8);
        keys.forEach((key, colIndex) => {
            const val = formattedRow[key];
            doc.text(val, 42 + colIndex * colWidth, currentTableY + 6, {
                width: colWidth - 4,
                align: "left"
            });
        });

        currentTableY += rowHeight;
    });

    // Finalize page counting and headers
    drawHeaderAndFooter();
    doc.end();
};

module.exports = { generatePDF };
